### ISSUE TITLE
issues about sjoestroem data 

### ISSUE THREAD

**Issue by bilian1995** [mgraupe/CalciumBasedPlasticityModel#1]
Hi! I am planning to use the calcium-based learning model in my research, but I have some troubles in finding the "sjoestroem_regular_all.dat". Are they published? The data that I found in his website are quite different..
Thank you!

Roland

**Comment by mgraupe** [comment]
Indeed, the experimental data was not part of the repository. Thank you for pointing this out. It's added now. 

Yes, the plasticity data in response to spike-pairs presented at different frequencies is published in :
Sjöström PJ1, Turrigiano GG, Nelson SB. Rate, timing, and cooperativity jointly determine cortical synaptic plasticity. Neuron. 2001 Dec 20;32(6):1149-64.

Cheers,
Michael
